### ISSUE TITLE
Provide some examples?

### ISSUE THREAD

**Issue by phynet** [KenVanHoeylandt/Bolts-Swift#1]
Hello, thanks for the translation from obj-c to swift. Can you also provide some examples? I'm trying to translate my code from obj-c to swift using bolts and well...I'm a little bit lost.

Thank you. Greetings

**Comment by kenvanhoeylandt** [comment]
Hi! Sorry for the slow reply - I didn't notice I had messages.

My README.md only shows what I have added to the existing Bolts iOS library. More examples can be found on the Bolts page itself:
https://github.com/BoltsFramework/Bolts-iOS
They are available in Objective-C and its Swift translation. All examples on that page will also work with Bolts-Swift, as Bolts-Swift is dependent on it.

**Comment by phynet** [comment]
Thanks. Later that day I translated my objc to swift code.

**Comment by kenvanhoeylandt** [comment]
You're welcome!
Good luck with the project!

Kind regards,
Ken
